# Generated by Django 6.1.1 on 2026-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_requestresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='One or more numbers, comma-separated if needed', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('has_blood_bank', models.BooleanField(default=False)),
                ('is_24_7', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
